action_id: trunk-share-with-everyone
date: 2023-10-16 07:46:50
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1697442410
full_timestamp:
  nanos: 723187000
  seconds: 1697442410
trunk_version: 1.17.0
